name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: nightly
          combine: false

      - uses: actions/upload-artifact@v4
        with:
          name: BrokenHack
          path: ${{ steps.build.outputs.build-output }}
